services:
  - type: web
    name: bse-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "0"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CRON_SECRET_KEY
        sync: false
      - key: YAHOO_CACHE_TTL
        value: "60"
      - key: YAHOO_VERBOSE
        value: "0"
